chore: fall back to npm firebase package 3.5.0 (#532)
The current version, 3.6.0, causes the build to fail on Travis:
> firebase serve --port 4001
>
> Error: No project active, but project aliases are available.